spring.application.name=financial-tracker

spring.datasource.url=jdbc:mysql://localhost:3306/financial_tracker?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


spring.security.oauth2.client.registration.google.client-id=885316256157-9bosddc61mhieokop7u9v1nago38vr0c.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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


spring.security.oauth2.client.registration.github.client-id=Ov23lidWkSGwGM2JsEbe
spring.security.oauth2.client.registration.github.client-secret=8ee88c89f512c289f41171f9b1a23621b7395e67
spring.security.oauth2.client.registration.github.scope=read:user,user:email

#spring.security.oauth2.client.registration.microsoft.client-id=YOUR_MICROSOFT_ID
#spring.security.oauth2.client.registration.microsoft.client-secret=YOUR_MICROSOFT_SECRET

